[general]
static=yes
writeprotect=no
clearglobalvars=no

[from-users]
exten => _X.,1,NoOp(Registered user call to fixed SIP target)
 same => n,Dial(PJSIP/${EXTEN}@trunk-out,60)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Inbound from fixed trunk)
 same => n,Hangup()